"""Probe deterministic twin clean replay in a replay-locked v0.2 runtime."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import h5py
import numpy as np


def max_abs(left, right) -> float:
    return float(np.max(np.abs(np.asarray(left, dtype=np.float64) - np.asarray(right, dtype=np.float64))))


def state(env):
    return np.asarray(env.get_state()["states"]).copy()


def text(value):
    return value.decode("utf-8") if isinstance(value, bytes) else value


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--demo-id", required=True)
    parser.add_argument("--max-steps", type=int, default=150)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    from stage1.benchmark.simulator_replay import create_shaped_env

    env_a, _ = create_shaped_env(str(args.source))
    env_b, _ = create_shaped_env(str(args.source))
    try:
        with h5py.File(args.source, "r") as source:
            demo = source[f"data/{args.demo_id}"]
            actions = demo["actions"][: min(len(demo["actions"]), args.max_steps)]
            initial_state = demo["states"][0]
        # The XML is generated by the locked runtime itself, not derived from
        # the old source demonstration XML.
        canonical_xml = env_a.env.model.get_xml()
        payload = {"states": initial_state, "model": canonical_xml}
        env_a.reset(); env_a.reset_to(payload)
        env_b.reset(); env_b.reset_to(payload)
        rows = []
        stage_a = getattr(env_a.env, "staged_rewards", None)
        stage_b = getattr(env_b.env, "staged_rewards", None)
        for action_t, action in enumerate(actions):
            pre_a, pre_b = state(env_a), state(env_b)
            _, reward_a, _, _ = env_a.step(action)
            _, reward_b, _, _ = env_b.step(action)
            post_a, post_b = state(env_a), state(env_b)
            staged_a = np.asarray(stage_a(), dtype=np.float64).reshape(-1) if stage_a else np.zeros(0)
            staged_b = np.asarray(stage_b(), dtype=np.float64).reshape(-1) if stage_b else np.zeros(0)
            success_a = bool(env_a.is_success().get("task", False))
            success_b = bool(env_b.is_success().get("task", False))
            rows.append({
                "action_t": int(action_t),
                "states_pre_max_abs": max_abs(pre_a, pre_b),
                "states_post_max_abs": max_abs(post_a, post_b),
                "reward_abs": abs(float(reward_a) - float(reward_b)),
                "staged_max_abs": max_abs(staged_a, staged_b) if len(staged_a) else 0.0,
                "success_equal": success_a == success_b,
            })
        result = {
            "source": str(args.source),
            "demo_id": args.demo_id,
            "runtime_model_sha256": hashlib.sha256(canonical_xml.encode("utf-8")).hexdigest(),
            "steps": len(rows),
            "max_states_pre_abs": max((row["states_pre_max_abs"] for row in rows), default=None),
            "max_states_post_abs": max((row["states_post_max_abs"] for row in rows), default=None),
            "max_reward_abs": max((row["reward_abs"] for row in rows), default=None),
            "max_staged_abs": max((row["staged_max_abs"] for row in rows), default=None),
            "success_all_equal": all(row["success_equal"] for row in rows),
            "determinism_pass": bool(rows) and all(
                row["states_pre_max_abs"] <= 1e-10
                and row["states_post_max_abs"] <= 1e-10
                and row["reward_abs"] == 0.0
                and row["staged_max_abs"] == 0.0
                and row["success_equal"]
                for row in rows
            ),
            "rows": rows,
        }
    finally:
        env_a.close()
        env_b.close()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(json.dumps({key: value for key, value in result.items() if key != "rows"}, indent=2))


if __name__ == "__main__":
    main()
